AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  TargetEnvironment:
    Description: Name of your target environment which will be used as a suffix on
      created resources (dev, UAT, prod, ...)
    Type: String
    Default: prod
  SessionExpiry:
    Type: Number
    Description: The max contact (call) session duration in seconds. Temporary credentials
      will expire after this time.
    Default: 3600
Metadata:
  AWS::ServerlessRepo::Application:
    Name: Zendesk-Connect-authorization
    Description: Enables the Amazon Connect app for Zendesk to access the Connect
      API. Required for certain functionality like pause and/ resume call recordings.
    Author: VoiceFoundry-APAC
    SpdxLicenseId: GPL-3.0-or-later
    LicenseUrl: s3://214558022353-connect-zendesk-ap-southeast-2/zendesk-add-ons/connect-auth/e62637ea8a114355b985fd86c9ffbd6e
    ReadmeUrl: s3://214558022353-connect-zendesk-ap-southeast-2/zendesk-add-ons/connect-auth/82013e4428c4c390f6611ac3ac1b6586
    Labels:
    - Connnect
    - Zendesk
    - Pause-Resume
    - Recording
    HomePageUrl: https://github.com/voicefoundryap/amazon-connect-for-zendesk/tree/master/add-ons/connect-auth
    SemanticVersion: 1.0.0
    SourceCodeUrl: https://github.com/voicefoundryap/amazon-connect-for-zendesk/tree/master/add-ons/connect-auth
Resources:
  policyConnectFromZendesk:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName:
        Fn::Sub: connect-from-zendesk-${TargetEnvironment}
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Action:
          - connect:UpdateContactAttributes
          - connect:ResumeContactRecording
          - connect:SuspendContactRecording
          Resource:
            Fn::Sub: arn:${AWS::Partition}:connect:${AWS::Region}:${AWS::AccountId}:instance/*
  roleAccountAssumeConnect:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: account-assume-connect-${TargetEnvironment}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS:
            - Fn::Sub: arn:${AWS::Partition}:iam::${AWS::AccountId}:root
          Action:
          - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
      - Ref: policyConnectFromZendesk
  policyLambdaAssumeRole:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName:
        Fn::Sub: lambda-assume-role-${TargetEnvironment}
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - sts:AssumeRole
          Resource:
            Fn::Sub: ${roleAccountAssumeConnect.Arn}
  functionContactInit:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: zendeskContactInit-${TargetEnvironment}
      Description: Triggered from contact flow, it retrieves temporary credentials
        for Zendesk to access Connect API
      Runtime: nodejs12.x
      Handler: index.handler
      CodeUri: s3://214558022353-connect-zendesk-ap-southeast-2/zendesk-add-ons/connect-auth/a80b68919eae37b5758d2a3df2c3d06f
      Timeout: 8
      Policies:
      - AWSLambdaBasicExecutionRole
      - Ref: policyLambdaAssumeRole
      Environment:
        Variables:
          ASSUME_ROLE:
            Fn::Sub: ${roleAccountAssumeConnect.Arn}
          SESSION_EXPIRY:
            Ref: SessionExpiry
