AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  TargetEnvironment:
    Description: Name of your target environment (dev, UAT, prod, ...)
    Type: String
    Default: prod
  ConnectBucket:
    Description: S3 bucket name for your Connect data storage
    Type: String
    Default: connect-xyz
    AllowedPattern: (?=^.{3,63}$)(?!^(\d+\.)+\d+$)(^(([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])\.)*([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])$)
  ConnectMasterKeyId:
    Description: Key ID of your KMS customer managed key with alias connect-master-key
    Type: String
  ZendeskEmailID:
    Type: String
    Description: The Zendesk Admin Email ID for the selected Zendesk Instance
  ZendeskToken:
    Type: String
    Description: Zendesk Token with Admin privileges.This needs to be generated as
      a pre-requisite for this installation.
    NoEcho: true
  ZendeskURL:
    Type: String
    Description: Zendesk URL (https://<your-name>.zendesk.com).The Zendesk instance
      needs to be created as a pre-requisite for this installation.
    AllowedPattern: https://[a-zA-Z0-9-.]+.zendesk.com$
    ConstraintDescription: Endpoint must be a valid Zendesk Host URL. For example,
      https://voicefoundryap.zendesk.com
  ConnectURL:
    Type: String
    Description: Connect instance URL (either https://<connect-instance>.awsapps.com,
      or https://<connect-instance>.my.connect.aws).
    AllowedPattern: https://[a-zA-Z0-9-.]+.(awsapps.com|my.connect.aws)$
    ConstraintDescription: Endpoint must be a valid Connect instance URL.
  TimeZone:
    Type: String
    Description: Time zone (eg. Australia/Sydney) to be used when linking to Connect
      Contact Trace Records. For a full list see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
Metadata:
  AWS::ServerlessRepo::Application:
    Name: Contact-Lens-Analysis-for-Zendesk
    Description: Appends Amazon Contact Lens analysis to a corresponding Zendesk Support
      ticket. To be used with Amazon Connect app for Zendesk.
    Author: VoiceFoundry-APAC
    SpdxLicenseId: GPL-3.0-or-later
    LicenseUrl: s3://214558022353-connect-zendesk-ap-southeast-2/zendesk-add-ons/contact-lens//e62637ea8a114355b985fd86c9ffbd6e
    ReadmeUrl: s3://214558022353-connect-zendesk-ap-southeast-2/zendesk-add-ons/contact-lens//803b009a28d964c57d559c9f949a95f0
    Labels:
    - Connnect
    - Contact-Lens
    - Zendesk
    - Sentiment
    - Transcript
    HomePageUrl: https://github.com/voicefoundryap/amazon-connect-for-zendesk/add-ons/contact-lens
    SemanticVersion: '0.0.5'
    SourceCodeUrl: https://github.com/voicefoundryap/amazon-connect-for-zendesk/add-ons/contact-lens
Resources:
  tableZendeskRetries:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Sub: zendeskUpdateRetries-${TargetEnvironment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
      - AttributeName: contactId
        AttributeType: S
      KeySchema:
      - AttributeName: contactId
        KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: expires
        Enabled: true
  functionUpdateTicket:
    Type: AWS::Serverless::Function
    DependsOn: tableZendeskRetries
    Properties:
      FunctionName:
        Fn::Sub: contactLensZendeskUpdate-${TargetEnvironment}
      Description: Triggered on upload of Contact Lens analysis to S3 bucket, it finds
        and updates the matching Zendesk support ticket
      Runtime: nodejs12.x
      Handler: index.handler
      CodeUri: s3://214558022353-connect-zendesk-ap-southeast-2/zendesk-add-ons/contact-lens//b8dc42d486cebb09d843c1462d389e3f
      Timeout: 240
      Policies:
      - AWSLambdaBasicExecutionRole
      - S3ReadPolicy:
          BucketName:
            Ref: ConnectBucket
      - KMSDecryptPolicy:
          KeyId:
            Ref: ConnectMasterKeyId
      - DynamoDBCrudPolicy:
          TableName:
            Ref: tableZendeskRetries
      Environment:
        Variables:
          CONTACT_LENS_BUCKET:
            Ref: ConnectBucket
          CONNECT_INSTANCE_URL:
            Ref: ConnectURL
          RETRIES_TABLE:
            Ref: tableZendeskRetries
          EXCLUSION_KEY: no-support-ticket
          INCLUSION_KEY: support-ticket
          EXPIRES_MINUTES: 20
          MAX_QUERY_LENGTH: 1024
          TIME_ZONE:
            Ref: TimeZone
          ZD_EMAIL:
            Ref: ZendeskEmailID
          ZD_TOKEN:
            Ref: ZendeskToken
          ZD_URL:
            Ref: ZendeskURL
      Events:
        scheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
            Name:
              Fn::Sub: zendeskRetrySchedule-${TargetEnvironment}
            Description: invokes contactLensZendeskUpdate lambda which retries finding
              a matching support ticket
